### ISSUE TITLE
Substring match wins over complete string match

### ISSUE THREAD

**Issue by commandline** [acuminous/yadda#161] opened 2015-07-28 20:50 UTC
To signatures for steps in a step library: "the user adds an element" and "the user adds an element with an attribute". In the feature file, the step is "Given the user adds an element with an attribute".

Expect the more complete macro signature to match but in actuality, appears to be order dependent. If the shorter, partial match is .defined for the library 1st, that step definition is used; the 2nd, exact match to the step in the feature only matches if it is .defined first.

**Comment by cressie176** [comment] 2015-07-28 22:15
Yadda **should** find all compatible steps, then normalise their step signatures, then calculate the Levenshtein distance between the normalised reg ex and the input text. If two steps have the same Levenshtein distance then Yadda reports an ambiguous step.

Can you paste the step definitions please?

**Comment by commandline** [comment] 2015-07-28 22:35
I will do one better, I will fork and craft a unit test. I realized after writing this that we are on 0.11, just updated us to 0.15.1, so worthwhile to see if we can even replicate the problem with the much newer version.

**Comment by cressie176** [comment] 2015-07-28 23:27
Great thanks.

**Comment by commandline** [comment] 2015-07-29 16:03
See: https://github.com/acuminous/yadda/pull/162

Seems like the changes since 0.11 may already address this. I updated our project to use 0.15.1, didn't break anything. I will check in with my team mate who encountered this and re-test our step library with the newer version. If all checks out, I will close this issue.

**Comment by cressie176** [comment] 2015-07-29 17:19
Thanks for the update and PR. I'm still going to investigate as I haven't made significant changes to any of the code in this area for a very long time. Possibly not since the first release

**Comment by commandline** [comment] 2015-07-29 17:35
It is possible the unit test in my PR isn't exercising the same thing we saw. If our manual testing still breaks in the way I described, I will try to craft another unit test or maybe a dummy project that demonstrates the surprising behavior.

**Comment by cressie176** [comment] 2015-07-29 21:33
Thanks, really appreciate it.

**Comment by commandline** [comment] 2015-07-29 21:34
So, we are still seeing the undesirable/surprising match between our feature file and our step definitions. Let me see what I can do to try to express this in a failing unit test.

**Comment by cressie176** [comment] 2015-07-30 21:48
I just tried the test in your PR against 0.11.0 and the test passes. I also tried constructing a feature filed on the test, but that had no issues either. Is it possible for you to provide the exact step text and definition?

**Comment by cressie176** [comment] 2015-08-09 08:41
Any further info?

**Comment by commandline** [comment] 2015-08-10 17:45
Sorry, haven't had a chance to reproduce this here, yet. I don't think I can share our Gherkin, unfortunately, so will have to try to reproduce the problem with some fresh files for the purpose.

**Comment by cressie176** [comment] 2015-08-11 06:41
OK. Thanks for the update

**Comment by cressie176** [comment] 2015-09-03 05:44
Any luck?

**Comment by commandline** [comment] 2015-09-03 17:28
I am so swamped, mostly because yadda works for well in every other way. ;) It is still on my short list to get you some code that exercises this, especially since I just got bit by the problem, again, in my own (private) project.

**Comment by cressie176** [comment] 2015-09-04 07:14
No problem - I know how *swamped* feels! Glad you're enjoying using Yadda otherwise

**Comment by commandline** [comment] 2015-09-04 15:48
I *was* going to work on some sample or test code for these two issues, today, but now one of our tests is showing me a random segfault. I will get to these, I promise, I want to support this awesome project that has helped my work so much.

**Comment by cressie176** [comment] 2015-09-04 18:51
Seg fault can be down to your version of node. If on 0.10.x try upgrading
to the latest patch release 0.10.40 I think

On Friday, 4 September 2015, Thomas Gideon <notifications@github.com> wrote:

> I *was* going to work on some sample or test code for these two issues,
> today, but now one of our tests is showing me a random segfault. I will get
> to these, I promise, I want to support this awesome project that has helped
> my work so much.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/acuminous/yadda/issues/161#issuecomment-137773252>.
>


-- 
http://peaceoneday.org/

**Comment by cressie176** [comment] 2015-12-06 16:03
Going to close this as I can't reproduce and have no other reported issues. If you do get time to look into it happen to reopen.

**Closed by cressie176** 2015-12-06 16:03 UTC
