### ISSUE TITLE
Regression in 0.17.5 - done callback invoked multiple times

### ISSUE THREAD

**Issue by DanielHeath** [acuminous/yadda#210] opened 2016-04-21 03:46 UTC
I'm using the step level mocha plugin and tried upgrading today.
I have been using https://github.com/ask-izzy/ask-izzy/blob/master/test/support/yadda-promise.js to convert steps that return promises into steps that work with the callback API. 

When upgrading I get mocha complaining that the done callback is called multiple times when a failure occurs. Did not happen in 0.17.4.

**Comment by cressie176** [comment] 2016-04-21 07:20
Sorry you're having problems. Will investigate.

**Comment by cressie176** [comment] 2016-04-22 08:11
I checked out ask-izzy but wasn't able to run the test. Also not sure what to make of
```
async function waitForResultCount(
    expected: number,
): Promise<void> {
```

Would it be possible for you to reproduce with a simpler test case?

Also 0.17.5 included a PR that enables steps to return promises. You might not need to unpromisify any more.

Sorry I'm not more help.

**Comment by DanielHeath** [comment] 2016-04-25 23:46
I'll have a look, thanks :)

I would remove unpromisify, but it provides a quite convenient way to pause execution when a test fails (so I can poke at the browser).

**Comment by nareshbhatia** [comment] 2016-06-02 04:35
I am running into the exact same issue - even though I am not using yadda-promise. Version 17.4 is running fine, but version 17.5 is producing the following error:

    Error: done() called multiple times

Unfortunately I am not able to reproduce the issue in a simpler project.

Here's my test.js file in case that is helpful:

    var Promise = require("bluebird");
    var pgPromise = require("pg-promise");

    var Yadda = require('yadda');
    Yadda.plugins.mocha.StepLevelPlugin.init();

    var pgp = null;
    var db = null;

    // Establish before hook - this will run before any feature file is executed
    before(initDb);

    // Establish after hook - this will run after all feature files have been executed
    after(releaseDb);

    new Yadda.FeatureFileSearch('./test/features').each(function(file) {

        featureFile(file, function(feature) {

            var libraries = require_feature_libraries(feature);
            var yadda = Yadda.createInstance(libraries);

            scenarios(feature.scenarios, function(scenario) {

                // Truncate tables before every scenario
                before(truncateTables);

                var ctx = {};
                steps(scenario.steps, function(step, done) {
                    yadda.run(step, { ctx: ctx }, done);
                });
            });
        });
    });

    function require_feature_libraries(feature) {
        return feature.annotations.libraries.split(', ').reduce(require_library, []);
    }

    function require_library(libraries, library) {
        return libraries.concat(require('./steps/' + library + '.steps'));
    }

    function initDb(done) {
        var pgpOptions = {
            promiseLib: Promise
        };

        var dbConfig = {
            host: 'localhost',
            port: 5432,
            database: 'test',
            user: '',
            password: ''
        };

        // Initialize pg-promise & db
        pgp = pgPromise(pgpOptions);
        db = pgp(dbConfig);
        done();
    }

    function releaseDb(done) {
        pgp.end();
        done();
    }

    function truncateTables(done) {
        return db.result('truncate table test1 test2 cascade')
            .then(function() {
                done();
            });
    }

**Comment by cressie176** [comment] 2016-06-02 11:51
@nareshbhatia and you link or paste to some of your steps please?

**Comment by cressie176** [comment] 2016-06-02 20:41
Still not able to reproduce, however I did go through an refactor the code that may be causing the problem. I doubt my changes will have fixed the issue but if you're able to try them out I'd appreciate it

https://github.com/acuminous/yadda/tree/issue-210

Also a stacktrace would be helpful

**Comment by cressie176** [comment] 2016-06-02 21:36
The only way I've been able to reproduce is by mixing promises and callbacks...
```
.when("$NUM green bottle accidentally falls", function(number_of_falling_bottles, next) {
    return new Promise(function(resolve, reject) {
        wall.fall(number_of_falling_bottles);
        resolve(true);
        next();
    });
})
```
or
```
.when("$NUM green bottle accidentally falls", function(number_of_falling_bottles, next) {
    return new Promise(function(resolve, reject) {
        wall.fall(number_of_falling_bottles);
        resolve(true);
    }).then(function() {
        next()
    });
})
```
however if returning a promise to yadda from your step, there's no need to use callbacks
```
.when("$NUM green bottle accidentally falls", function(number_of_falling_bottles) {
    return new Promise(function(resolve, reject) {
        wall.fall(number_of_falling_bottles);
        resolve(true);
    });
})
```

**Comment by nareshbhatia** [comment] 2016-06-02 22:14
@cressie176, thanks for following up. In that sense, I am definitely mixing promises and callbacks. For example:

    .when('$username asks to show all projects', function(username, next) {
        var self = this;
        projectService.getProjects(username)
            .then(function(projects) {
                self.ctx.projects = projects;
                next();
            });
    })

I did not even know that yadda can accept promises. Is this something that has changed recently? I was just going by the docs in README.

I will certainly try returning promises and also your latest refactoring.

**Comment by nareshbhatia** [comment] 2016-06-02 23:20
Changed the code to return a promise, but yadda does not seem to wait for the promise to complete. It is moving straight through to the next step and fails. Here's my modified code:

    .when('$username asks to show all projects', function(username) {
        var self = this;
        projectService.getProjects(username)
            .then(function(projects) {
                self.ctx.projects = projects;
                return projects;
            });
    })

I also tried the refactored branch (issue-210), but no luck. I tried this branch both ways, trying to return a promise vs. calling next().

**Comment by nareshbhatia** [comment] 2016-06-02 23:35
Reading the release notes, I see that release 0.17.5 is the one that allowed mixing of sync and async. Unfortunately that's exactly what is breaking my tests. Please let me know your thoughts looking at my experiments above. I can try other things.

**Comment by cressie176** [comment] 2016-06-03 07:01
@nareshbhatia thanks for trying the refactored branch. I'm a little out of date updating the docs. The promise support was a 1 line PR + tests that didn't look like it was going to cause any problems. I should have rev'd the minor version, rather than publishing as patch. my bad.

> I am definitely mixing promises and callbacks. For example:
```
    .when('$username asks to show all projects', function(username, next) {
        var self = this;
        projectService.getProjects(username)
            .then(function(projects) {
                self.ctx.projects = projects;
                next();
            });
    })
```
The above should be fine because the step doesn't **return** a promise. When your step returns a promise [yadda invokes](https://github.com/acuminous/yadda/blob/issue-210/lib/Macro.js#L51) ```then(function() { next() })```. This is to avoid you having to write code like
```
    .when("$NUM green bottle accidentally falls", function(number_of_falling_bottles, next) {
        new Promise(function(resolve, reject) {
            wall.fall(number_of_falling_bottles);
            resolve(true);
        }).then(function() { 
            next()
        });
    })
```
With promise support you omit next and write
```
    .when("$NUM green bottle accidentally falls", function(number_of_falling_bottles) {
        return new Promise(function(resolve, reject) {
            wall.fall(number_of_falling_bottles);
            resolve(true);
        })
    })
```
but you have to *return* the promise otherwise the step will be treated synchronously and just run through.

**Comment by nareshbhatia** [comment] 2016-06-03 17:16
That sounds pretty straightforward. So none of the steps in my codebase are returning promises - they are all coded in the pre-0.17.5 way - calling `next()` explicitly. I can do some more investigation on what's tripping up yadda. If you have any ideas, please feel free to throw them at me!

**Comment by cressie176** [comment] 2016-06-04 00:45
Thanks for investigating - I'm having no luck reproducing with your step. The Yadda code which calls next is here https://github.com/acuminous/yadda/blob/issue-210/lib/Macro.js#L50-L52. If the step returns a promise, Yadda calls then, passing a guarded next. If the step is synchronous (determined by the number of arguments compared to the number of parsed parameters) Yadda calls next.

I'd be interested to know what happens with your steps

**Comment by nareshbhatia** [comment] 2016-06-04 03:38
@cressie176, I was finally able to reproduce the problem in a small example. Please see this: https://github.com/nareshbhatia/yadda-issue-210. Hope this helps you pinpoint the problem.

**Comment by cressie176** [comment] 2016-06-04 05:43
@nareshbhatia Thanks for creating the example. The problem is that you're returning a promise AND calling next in your step. I've submitted a [PR](https://github.com/nareshbhatia/yadda-issue-210/pull/1) which will hopefully explain it more clearly.

**Comment by nareshbhatia** [comment] 2016-06-04 11:18
Ouch, that's my bad. My brain was wired to look for a `next` in the parameter list and matching it with a `next()` call. I completely forgot about the requirement that I should not be returning promises - which is also wired into my brain whenever I use promises. I think the solution you provide is a good one, i.e. to remove the next and return a promise - which is consistent with best practices. I will switch over to this convention.

Thanks so much for helping out with this.

**Comment by cressie176** [comment] 2016-06-04 13:47
Well it's my bad for not updating the docs or bumping the minor version. Going to leave the issue open though as @DanielHeath is still experiencing something similar. Suspect the root cause is the same but my typescript isn't good enough to debug.

**Comment by cressie176** [comment] 2016-06-14 16:50
@DanielHeath closing this as I can't reproduce from the ask-izzy test suite. Suspect it will be the same problem @nareshbhatia was having (calling next and returning a promise). If you get the chance to setup a standalone test case please re-open / post a new issue. 

Sorry for the trouble by adding what I thought was a non breaking change in a patch release.

**Closed by cressie176** 2016-06-14 16:50 UTC
Labels: awaiting response
